### ISSUE TITLE
Deprecation error while running cake bake

### ISSUE THREAD

**Issue by ericlacasse-cofomo** [WyriHaximus/TwigView#100]
While running any `cake` command in command line, we get the following error message.

> Deprecated Error: Checking a single plugin with Plugin::loaded() is deprecated. Use Plugin::isLoaded() instead. - C:\path\to\project\vendor\wyrihaximus\twig-view\config\bootstrap.php, line: 11                                                                  You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in [C:\path\to\project\vendor\cakephp\cakephp\src\Core\functions.php, line 311]

I know that the issue is fixed in this commit (https://github.com/WyriHaximus/TwigView/commit/8b0e05b7b8042b5a9d870a4d9435674d918cceb3), but can you tell me when a new release with this commit would be released? This is the last thing holding back our migration to CakePHP 3.7.0. We can always run the patch manually, but this would go against our deployment procedure which rely on the composer packages.

Thank you for your cooperation and feedback.

**Comment by WyriHaximus** [comment]
Just tagged [`v4.3.7`](https://github.com/WyriHaximus/TwigView/releases/tag/4.3.7) with this fix :+1: .
