### ISSUE TITLE
How does it work on cakephp3 ?

### ISSUE THREAD

**Issue by y4nn0ff** [WyriHaximus/TwigView#14]
Hi,

Here what i did : 
Install via twigview via composer
```
composer require wyrihaximus/twig-view 
Using version dev-master for wyrihaximus/twig-view
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing twig/twig (v1.23.1)
    Downloading: 100%         

  - Installing asm89/twig-cache-extension (1.1.0)
    Downloading: 100%         

  - Installing wyrihaximus/twig-view (dev-master ac044a2)
    Cloning ac044a256c9cc29a30c402fcbd3c2cd1d214729e

Writing lock file
Generating autoload files
```

Load plugin in boostrap:
```
Plugin::load('Migrations');
Plugin::load('WyriHaximus/TwigView', [
	'bootstrap' => true,
]);
```

Initialise $viewClass : 
```
src/Controller/AppController.php
class AppController extends Controller
{

	public $viewClass = '\WyriHaximus\TwigView\View\TwigView';
        .....
}
```

First little issue, these lines stop working
```
src/Template/Layout/default.ctp
<?= $this->fetch('meta') ?>
    <?= $this->fetch('css') ?>
    <?= $this->fetch('script') ?>
```

But the real probleme is assign variable and use it in template, I did:
```
src/Controller/AppController.php
class AppController extends Controller
{

	public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
		
		$this->set('title',"test twig");
	
    }
}
```

```
src/Template/Layout/default.ctp
{{ title }}
<?= $this->fetch('content') ?>
```

And the render of variable is `{{ title }}` instead of `test twig` when i load the page on a browser.

Where is the mistake ? could you help me ?

**Comment by WyriHaximus** [comment]
Change your template file extension to `.tpl` instead of `.ctp`. Also you can't mix cake's template syntaxt and twig's

**Comment by y4nn0ff** [comment]
Thanks, it works.

But what is the twig syntax for this : 
```
$this->Html->css('base.css')
$this->Flash->render()
$this->fetch('css')
$this->fetch('content')
```

And what is the best practice to use angular and twig without conflict (because curly bracket) with you module ?

Regards ;)

**Comment by WyriHaximus** [comment]
The first question is easy: 

```twig
{{ html.css('base.css') }}
{{ flash.render() }}
{{ _view.fetch('css') }}
{{ _view.fetch('content') }}
```

Give me a couple of days to come back with you on the second question as it will require a new feature #15

**Comment by y4nn0ff** [comment]
Good, thanks ;)

is there a documention anywhere for this ? (html,flash,_view) to avoid these questions ;)

Good luck to develop the #15

**Comment by WyriHaximus** [comment]
Yes there is: https://github.com/WyriHaximus/TwigView#helpers

**Comment by y4nn0ff** [comment]
there are something weird :s 

{{ html.* }}, {{ flash.* }}, en {{ _view.fetch('css') }} write nothing in the DOM when it's rendered in a browser. And {{ _view.fetch('content') }} display the html code in browser.

```
&lt;h1&gt;Connexion&lt;/h1&gt;
&lt;form method="post" accept-charset="utf-8" action="/users/login"&gt;&lt;div style="display:none;"&gt;&lt;input type="hidden" name="_method" value="POST"/&gt;&lt;/div&gt;&lt;input type="text" name="email"/&gt;&lt;div class="input password"&gt;&lt;label for="password"&gt;Password&lt;/label&gt;&lt;input type="password" name="password" id="password"/&gt;&lt;/div&gt;&lt;button type="submit"&gt;Login&lt;/button&gt;&lt;/form&gt;
```
I must miss something...

**Comment by WyriHaximus** [comment]
Take a look at [`dump`](http://twig.sensiolabs.org/doc/functions/dump.html) (the twig site in general is very useful). (Using x.* also won't do anything, at least not what you want.) Also all output is encoded by default for security reasons. Both [`raw`](http://twig.sensiolabs.org/doc/filters/raw.html) and [`autoescape`](http://twig.sensiolabs.org/doc/tags/autoescape.html) can help you with this. Also this is where the config feature I'm working on comes in handy: http://twig.sensiolabs.org/doc/api.html#environment-options

**Comment by visonforcoding** [comment]
Could I use Twig layout syntax , for example , extend include  block . And how can i config the twig compile dir  . can you give more information about it .Thanks ,wait for your reply

**Comment by WyriHaximus** [comment]
Tackled this in: https://github.com/WyriHaximus/TwigView/releases/tag/3.2.0

**Comment by tolawho** [comment]
@WyriHaximus I generate a link like: /users/delete/id but it not working
Example:
In ctp template:
`<?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $user->id], ['confirm' => __('Are you sure you want to delete # {0}?', $user->id)]) ?>`

In twig template:
`{{ Form.postLink(__('Delete'),{'action' : 'delete', user.id },{'confirm' : __('Are you sure you want to delete # {0}?', user.id),'class':'button03'})|raw }}`
Error found at {'action' : 'delete', **user.id** }
![image](https://cloud.githubusercontent.com/assets/12527881/14338752/98507768-fca3-11e5-8940-c759c73491f1.png)
If i use a colon like: {'action' : 'delete', **'id': user.id** } => my result is `/users/delete?id=2` (Rigth result is /users/delete/2)

Please help!

**Comment by WyriHaximus** [comment]
Try: 
```twig
{'action' : 'delete', 0: user.id }
```

**Comment by ozee31** [comment]
Or use concatenation : 

```twig
{'action': 'delete/' ~ user.id}
```

**Comment by WyriHaximus** [comment]
@ozee31 thank you, I wasn't aware of that. I've created a new PR (#22) to add that to the documentation :+1: . Merging it tonight unless someone has feedback
