### ISSUE TITLE
Testing problem

### ISSUE THREAD

**Issue by ozee31** [WyriHaximus/TwigView#17]
Hi,

I have a problem when i test my controllers. All functions are unrecognized ("__()", "explode()" ...).
In my browser it's works.

In vendor/twig/twig/lib/Twig/Environment.php i have in `$this->extensions`
"core, escaper, optimizer, string_loader, debug, i18n ..."  
But in test i have just :
"core, escaper and optimizer"  
  
The class WyriHaximus\TwigView\Event\ExtensionsListener are not called by bootstrap.php (l.7) in test.

Do you have an explanation ? Thank You.

**Comment by WyriHaximus** [comment]
Be sure to include the bootstraps file when testing. Are you loading the plugin when you run your tests the way you do when you run it through the browser?

**Comment by ozee31** [comment]
Ok,
```PHP
Plugin::load('WyriHaximus/TwigView', [
            'bootstrap' => true,
        ]);
```
Doesn't work in `config/bootstrap.php` or `tests/bootrap.php` during test.

I added this code in `setup` function and it's work.

**Comment by WyriHaximus** [comment]
Great, might be because cake resets the state of the system between tests. Glad you solved it :+1:

**Comment by lemonCMS** [comment]
Could this solution please be added to the readme, we were busy for hours trying to figure this out.

Thanks in advance.

**Comment by WyriHaximus** [comment]
Feel free to open a PR adding that to the readme @lemonCMS 👍
