### ISSUE TITLE
Problem with extend common view

### ISSUE THREAD

**Issue by ozee31** [WyriHaximus/TwigView#19]
Hi,

I have a problem with Extending Views.

I have a layout default.tpl
```twig
<!DOCTYPE html>
<html>
<head>...</head>
<body>
    <header>
        {% if auth %}
            {% element 'nav' %}
        {% endif %}
        {{ _view.fetch('header')|raw }}
    </header>

    <section id="{{ page_id }}" class="js-container container-fluid">
        <div>
            {{ Flash.render()|raw }}
        </div>

        {{ _view.fetch('content')|raw }}
    </section>
</body>
```

In Common have a view content_sidebar.tpl
```twig
<div class="row">
    <div class="col-lg-2 col-md-3" style="background-color:green; height: 200px;">
        Sidebar
        {{ _view.fetch('sidebar')|raw }}
    </div>

    <div class="col-lg-10 col-md-9" styles="background-color:red; height: 200px;">
        Content
        {{ _view.fetch('content')|raw }}
    </div>
</div>
```

Extends this view in Users/view.tpl doesn't works

## First test
```twig
{% extends 'Common/content_sidebar' %}

{{ _view.start('sidebar') }}
    <p>Hi</p>
{{ _view.end() }}

<p>Plop</p>
```
Result :
A template that extends another one cannot have a body in "/var/www/html/app/src/Template/Users/view.tpl" at line 6. 

## Second test
```twig
{{ _view.extend('/Common/content_sidebar') }}

{{ _view.start('sidebar') }}
    <p>Hi</p>
{{ _view.end() }}

<p>Plop</p>
```
Result :
Display just <p>Plop</p>, no display Common's view

Thank you for your help

**Comment by WyriHaximus** [comment]
Hey this sounds more of a twig issue, take a look at this http://stackoverflow.com/questions/19040803/symfony-twig-cant-extend-a-template-when-displaying-a-grid-with-apydatagridbund and this http://twig.sensiolabs.org/doc/tags/extends.html

**Comment by ozee31** [comment]
Ok think you

**Comment by WyriHaximus** [comment]
Let me know how it works out. Planning to add information like this to the readme/docs soon, your input is appreciated :+1:

**Comment by ozee31** [comment]
It's a good idea
