### ISSUE TITLE
Update composer.json to allow twig 3.0

### ISSUE THREAD

**Issue by othercorey** [WyriHaximus/TwigView#219]
With twig 3.0 out, can you update the composer.json dependency to allow it? This is for dev-master with cakephp 4.0.

`^2.4.3|^3.0`

https://packagist.org/packages/twig/twig#v3.0.0

Unless you're using the non-namespaced classes, I don't think there will be an issue.

https://symfony.com/blog/preparing-your-applications-for-twig-3

**Comment by othercorey** [comment]
Looks like twig-extensions needs a branch for twig 3.0 support as they have 1.x support in the master branch still.

https://github.com/jasny/twig-extensions

**Comment by ADmad** [comment]
`jasny/twig-extensions` now have v1.3 released which supports Twig 3, we can now move ahead with updating the twig version constraint for TwigView.

**Comment by ADmad** [comment]
The other two dependencies `aptoma/twig-markdown` and `asm89/twig-cache-extension` will also need a new releases :/

**Comment by ADmad** [comment]
https://github.com/aptoma/twig-markdown/pull/34

**Comment by ADmad** [comment]
There seems to be an official markdown plugin too https://github.com/twigphp/markdown-extra, so perhaps `aptoma/twig-markdown` should be replaced with that?

`asm89/twig-cache-extension` also seems to be unmaintained. It was meant to be replaced by https://github.com/twigphp/twig-cache-extension but even that doesn't have any activity and no releases.

**Comment by othercorey** [comment]
I'm using the markdown-extra package with twig 3.

**Comment by WyriHaximus** [comment]
Any objections against going 3.0 only?

**Comment by ADmad** [comment]
> Any objections against going 3.0 only?

None from me. Twig 3 requires 7.2+ which is inline with Cake 4.

**Comment by ADmad** [comment]
@WyriHaximus Is the `asm89/twig-cache-extension` dependency essential for TwigView's working? Cause I don't see it getting updated to support Twig 3 anytime soon.

**Comment by ADmad** [comment]
Unless someone has the time and motivation to get `asm89/twig-cache-extension` or `twigphp/twig-cache-extension` to do a Twig 3 compatible release the best course of action right now would be simply replace `aptoma/twig-markdown` with `twigphp/markdown-extra` and release TwigView 5 without support for Twig 3.

Currently Bake 2.0.0 had to be tagged with while using `dev-master` of this plugin which isn't very nice. So we need to come up with a short term solution quickly and look into supporting Twig 3 later.

**Comment by WyriHaximus** [comment]
@ADmad planned to do it today after dinner :). And no we don't need the cache extensions to work.

**Comment by ADmad** [comment]
@WyriHaximus Great to hear.

**Comment by WyriHaximus** [comment]
WIP PR: https://github.com/WyriHaximus/TwigView/pull/224

**Comment by WyriHaximus** [comment]
@ADmad locally all tests are passing, only need to get the markdown plugin in

**Comment by WyriHaximus** [comment]
[`5.0`](https://github.com/WyriHaximus/TwigView/releases/tag/5.0.0) is out :tada:
