### ISSUE TITLE
Accessing Helpers 

### ISSUE THREAD

**Issue by HavokInspiration** [WyriHaximus/TwigView#29]
While trying the plugin, I found out I could not use the Helpers name directly as specified in the doc :

```php
{{ Html.css('default.app.css')|raw }}
```

I had to call them as follows :

```php
{{ _view.Html.css('default.app.css')|raw }}
```

After digging a bit, I found out that I had to change the ``TwigView::generateHelperList()`` method to the following implementation for it to work :

```diff
diff --git a/src/View/TwigView.php b/src/View/TwigView.php
index af8bc77..06ed785 100644
--- a/src/View/TwigView.php
+++ b/src/View/TwigView.php
@@ -164,7 +164,7 @@ protected function getLoader()
     protected function generateHelperList()
     {
         $registry = $this->helpers();
-        $helpers = $registry->normalizeArray($this->helpers);
+        $helpers = $registry->normalizeArray($registry->loaded());
         foreach ($helpers as $properties) {
             list(, $class) = pluginSplit($properties['class']);
             $this->helperList[$class] = $this->{$class};

```

I'm working with CakePHP 3.3-beta2 on a PHP 5.5.30 install.
I'm loading my Helpers in the ``initialize()`` method of my AppView class.

Is it ok if I submit a pull request with this change or do you think that could cause issues ?

**Comment by WyriHaximus** [comment]
Yes please submit a pull request, that will also test it against different CakePHP versions and PHP versions :+1:

**Comment by HavokInspiration** [comment]
I opened PR #31
