### ISSUE TITLE
Smarty filetype extension

### ISSUE THREAD

**Issue by auburus** [WyriHaximus/TwigView#34]
It might be an odd question, but why are you using `.tpl` file extension instead of `.twig`? As far I can tell, `.tpl` is for the Smarty template syntax.

Thanks, and sorry if that's an stupid question.

**Comment by WyriHaximus** [comment]
That is more heritage than conscious decision. But you should be able to use the .twig extension since 3.2.2: https://github.com/WyriHaximus/TwigView/commit/c270b743f238a0955e1b14af814f660eca0f12ad 

P.S. There are no stupid questions

**Comment by inoas** [comment]
Could the docs be updated to recommend twig? It might also help some editors @ syntax highlightning?

**Comment by WyriHaximus** [comment]
I don't see why not, would you mind making a PR for that? :smile:

**Comment by inoas** [comment]
Ref: https://github.com/WyriHaximus/TwigView/pull/36
Ref: https://github.com/WyriHaximus/TwigView/pull/35

This issue can then be closed, my guess.

p.s.: @WyriHaximus I did not check the loading order of .twig vs .tpl - I assumed it checks .twig first. I did the docs update quickly through GH and find/replace.

**Comment by auburus** [comment]
Extra fast! Thank you very much to the both of you :)

(And now I have to rename all the files... 😂😂😂).

**Comment by inoas** [comment]
@WyriHaximus btw, which filename extensions is TwigView generating via bake?

**Comment by WyriHaximus** [comment]
@inoas IIRC it checks .tpl first.

@inoas It creates `.twig` files: https://github.com/WyriHaximus/TwigView/blob/master/src/Shell/Task/TwigTemplateTask.php#L49

**Comment by inoas** [comment]
Could you do the PR to check .twig first? It would probably not be entirely BC however (the likelihood of issues is very small though)

**Comment by WyriHaximus** [comment]
Don't have time to go over everything tonight as I'm attending AmsterdamPHP. It should be as easy and switching over two lines in the twig view and changing one to .twig. As long as it behaves the same and tests don't fail I'm happy, honestly I've been considering of doing this :+1: .

**Comment by inoas** [comment]
1. I did the changes via Github. Ref: https://github.com/WyriHaximus/TwigView/pull/37 - please not that I changed the order. I hope that's what you imagined.
2. Can you think of a better exception message than this `new \Exception('You\'re not supposed to get here');`
3. OT: Are you presenting anything related to CakePHP ;)?

**Comment by inoas** [comment]
@auburus I think you can close this issue now.
