### ISSUE TITLE
Create release for a fix

### ISSUE THREAD

**Issue by ozee31** [WyriHaximus/TwigView#43]
Hi,

Can you make a release with the differents fix like: https://github.com/WyriHaximus/TwigView/commit/c786956cd52a0f440efa8acdfb60fda0275faaa3 ?

**Comment by WyriHaximus** [comment]
Yes they will be release, planning on releasing `4.0` due to some BC changes in the code since the last release. And want to add a few extra's for `4.0`

**Comment by HavokInspiration** [comment]
In the meantime, you can pin the version in composer to dev-master, e.g. in composer.json :

```
"wyrihaximus/twig-view": "dev-master"
```

**Comment by ozee31** [comment]
Ok think you

**Comment by WyriHaximus** [comment]
FYI I've added some things I want to add to the 4.0.0 mile stone: https://github.com/WyriHaximus/TwigView/milestone/2

**Comment by WyriHaximus** [comment]
Just released 4.0 and 3.3.1 with this and another fix
