### ISSUE TITLE
replace Cake\Utility\String

### ISSUE THREAD

**Issue by cewi** [WyriHaximus/TwigView#52]
Hi,
on cake 3.4.13 I get errors when using some filters. For example I tried to uses the 'tail'-filter and got:
> call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Utility\String' not found [ROOT/tmp/cache/twigView/92/92f2b8c028350aaa16ed3f034fd18af99b4bdbb3c04eb8818c6339fec8c6933b.php, line 76]

Cake\Utility\String is AFAIK replaced by Cake\Utility\Text ?

BTW: Thanks for this very helpful plugin!

**Comment by inoas** [comment]
Taking a look at
* https://github.com/WyriHaximus/TwigView/blob/master/src/Lib/Twig/Extension/Strings.php
* and https://book.cakephp.org/3.0/en/core-libraries/text.html
* and https://github.com/cakephp/cakephp/blob/master/src/Utility/String.php (fallback for PHP < 7.0.0)
* and https://book.cakephp.org/2.0/en/core-utility-libraries/string.html

Seems you are right and this will be noticed only once you switch to PHP 7.x

**Comment by WyriHaximus** [comment]
@cewi thanks for reporting 👍 ! Kind of surprised I haven't ran into this myself 🤐 . I'll release a new version tomorrow with @inoas PR (#53) in it

**Comment by cewi** [comment]
@WyriHaximus glad to hear and thanks again for your precious work. Looking forward to the next release.
@inoas You're right. I' m on php 7.1 Thanks for fixing!

**Comment by WyriHaximus** [comment]
FYI `4.0.5` with a fix for this has been released
