### ISSUE TITLE
wyrihaximus/twig-view 5.0: Upgrade twig/twig 2.0

### ISSUE THREAD

**Issue by inoas** [WyriHaximus/TwigView#56]
`$ composer outdated` shows me

	aptoma/twig-markdown                  2.0.0   3.0.0   Twig extension to work with Markdown content
	phpdocumentor/reflection-docblock     3.2.3   4.1.1   With this component, a library can provide support for annotations via DocBlocks or otherwise r...
	twig/twig                             v1.34.4 v2.4.3  Twig, the flexible, fast, and secure template language for PHP

phpdocumentor/reflection-docblock is an indirect dependency to phpunit 6.3.0. The other outdated dependencies are indirect dependencies to TwigView.

Any idea when there will be made progress here?

What I'd suggest is: If there is a lot of manual, tedious labour, I can try to make the core TwigView run with Twig 2.0 and you/other contributors with more knowledge about Twig can take a look at my PRs and help out with the library dependencies of 3rd parties that need updating for Twig 2.0?

I am also interested because I hope to gain some performance benefits from going to Twig 2.0

**Comment by WyriHaximus** [comment]
What I'de prefer to see with `5.0` is that TwigView is the core with just the core basics needed to run and any extra's in different packages. So if you want to look into that that would be greatly appreciated 👍. Currently focusing on getting tests in for everything that wasn't previously tested, wanted to do that before looking into `2.0`, I do have something local, could commit and push that but it ain't much.

**Comment by inoas** [comment]
Understand the tests so that there is a smooth ride upgrading by just fixing the tests and knowing where things break @ deprecation... 

I could take a look into upgrading all things to 2.x, 2.x namespaces, etc. but I don't feel comfortable breaking up the core into a micro + modules just yet; also I, myself, am only using parts of TwigView because I have to build my documents and document cells from database - so the experience is somewhat limited.

**Comment by WyriHaximus** [comment]
No worries about that, just focus on the core and ignore the rest while you work on that. I'll chop it up in different packages :+1: . Also I just pushed my work in the [twig-2](https://github.com/WyriHaximus/TwigView/tree/twig-2) branch, but it ain't much yet :(.

**Comment by inoas** [comment]
These two extensions are not maintained towards Twig 2.x
* "ajgl/breakpoint-twig-extension": "^0.3.0",
* "jasny/twig-extensions": "^1.0",

**Comment by inoas** [comment]
Closing as PR is open https://github.com/WyriHaximus/TwigView/pull/58
