### ISSUE TITLE
Warning with cakephp3.5

### ISSUE THREAD

**Issue by Orken** [WyriHaximus/TwigView#60]
Hello,

When i run TwigView on a CakePhp 3.5, with this code, 
```
{{ _view.assign('title', __("I'm title")) }}

{{ _view.start('header') }}
<p>I'm header</p>
{{ _view.end() }}

{{ _view.start('footer') }}
<p>I'm footer</p>
{{ _view.end() }}
<p>I'm content</p>
```

 i got those warnings :

>Warning (4096): Object of class App\View\AppView could not be converted to string [ROOT/tmp/cache/twigView/93/9354f08c1f47e54248409d9f11b74ab4e9f9d332c0df7ef5d38a4a486cb660cb.php, line 27]
>I'm header
>
>I'm title
>
>Warning (4096): Object of class App\View\AppView could not be converted to string [ROOT/tmp/cache/twigView/93/9354f08c1f47e54248409d9f11b74ab4e9f9d332c0df7ef5d38a4a486cb660cb.php, line 22]
> Warning (4096): Object of class App\View\AppView could not be converted to string [ROOT/tmp/cache/twigView/93/9354f08c1f47e54248409d9f11b74ab4e9f9d332c0df7ef5d38a4a486cb660cb.php, line 32]
> Warning (4096): Object of class App\View\AppView could not be converted to string [ROOT/tmp/cache/twigView/93/9354f08c1f47e54248409d9f11b74ab4e9f9d332c0df7ef5d38a4a486cb660cb.php, line 42]
> I'm content
> 
> Warning (4096): Object of class App\View\AppView could not be converted to string [ROOT/tmp/cache/twigView/93/9354f08c1f47e54248409d9f11b74ab4e9f9d332c0df7ef5d38a4a486cb660cb.php, line 37]
> I'm footer
```

Everything works fine with Cake3.4

Mitch

**Comment by inoas** [comment]
Could you also include 
`/tmp/cache/twigView/93/9354f08c1f47e54248409d9f11b74ab4e9f9d332c0df7ef5d38a4a486cb660cb.php`

**Comment by Orken** [comment]
You'll find it attached here.



[3d5e0211dc28c59bab413b8dac0ddbe4bc9521105d145d749578bb453c993008.zip](https://github.com/WyriHaximus/TwigView/files/1306649/3d5e0211dc28c59bab413b8dac0ddbe4bc9521105d145d749578bb453c993008.zip)

**Comment by Orken** [comment]
Sorry, I have included the wrong file, here's the good one.

[9354f08c1f47e54248409d9f11b74ab4e9f9d332c0df7ef5d38a4a486cb660cb.zip](https://github.com/WyriHaximus/TwigView/files/1310025/9354f08c1f47e54248409d9f11b74ab4e9f9d332c0df7ef5d38a4a486cb660cb.zip)

**Comment by robertpustulka** [comment]
Some methods return `$this` since 3.5.

I've found a workaround for this, use `none` filter:

```twig
{{ _view.assign('title', __("I'm title"))|none }}
```

**Comment by inoas** [comment]
What about
```twig
{% _view.assign('title', __("I'm title") %}
{{ _view.get('title') }}
```

**Comment by robertpustulka** [comment]
@inoas have you checked if your examples work, or maybe you are just guessing?

**Comment by inoas** [comment]
Half guessing. I do only use a few parts of TwigView in my projects and I am not using `_view.*`

Trying:
{% _view.assign('title', __("I'm title")) %} {# execute setter #} <= Not a valid tag
{{ _view.get('title') }} {# just echo #} <= not an existing property
{{ _view.title }} {# this may work as well, try-and-see #} <= not an existing property

p.s.: I could not even find the docs for `none` https://twig.symfony.com/doc/2.x/filters/index.html

**Comment by robertpustulka** [comment]
Ok, so please don't mislead people :)

`none` filter is provided by this plugin.

**Comment by inoas** [comment]
Ok, so please suggest to use dirty hacks :)
The problem here is that CakePHPs minor release is non-BC.

**Comment by robertpustulka** [comment]
As I said it is a *workaround* which actually **works**.

**Comment by inoas** [comment]
It does not.

You still need `{{ _view.fetch('title') }}` as `|none` will stop returning `$this` but not output the title as before as CakePHP 3.5 broke that feature non-BC.

**Comment by robertpustulka** [comment]
I'll ask again: have you tried this or still guessing?

**Comment by inoas** [comment]
Have you, I have.

**Comment by robertpustulka** [comment]
I use this workaround successfilly in my code.

Are we talking about the same?
```
{{ _view.assign('block', 'value')|none }}
{{ _view.fetch('block') }}

**Comment by inoas** [comment]
Yes that will work, despite being a hack (running `echo return`, looking at `WyriHaximus\TwigView\Lib\Twig\Extension\Strings`). Without the fetch call it won't work.

Can you see a better way to get around the hack required because of assign/set returning `$this` in CakePHP 3.5? The only way I found is creating quite a bunch of Twig-Tags as far as I understand: https://twig.symfony.com/doc/2.x/advanced.html#tags as `{% foo %}` seems only to allow DSL constructs and no Twig Simple Functions.

**Comment by markstory** [comment]
We should probably revert the changes in CakePHP then.

**Comment by inoas** [comment]
Well 3.5 has been out for some time now and that could have impacts /too/ so my suggestion (disclaimer @robertpustulka I have tried it, right now ;-) would be, to overwrite `assign()` and `__set()` in `class TwigView` to not return anything?

```php
// in TwigView:
    public function assign($name, $value)
    {
        $this->Blocks->set($name, $value);
    }
```

**Comment by markstory** [comment]
@inoas That is another option as well. I can put together a pull request for that if it would be helpful.

**Comment by inoas** [comment]
I'll wait for @WyriHaximus to chime in and if he concurs I will do that and hopefully also add working unit tests.

**Comment by robertpustulka** [comment]
@inoas This could work :+1:

**Comment by inoas** [comment]
A quick copy&adapt. I am not sure we ll need/want all of them (consistency? would you set the template path within a twig-template, ever, etc)?

```php
    /**
     * {@inheritDoc}
     * @return void
     */
    public function setTemplatePath($path)
    {
        parent::setTemplatePath($path);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function setLayoutPath($path)
    {
        parent::setLayoutPath($path);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function enableAutoLayout($enable = true)
    {
        parent::enableAutoLayout($enable);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function setTheme($theme)
    {
        parent::setTheme($theme);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function setTemplate($name)
    {
        parent::setTemplate($name);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function setLayout($name)
    {
        parent::setLayout($name);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function start($name)
    {
        parent::start($name);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function prepend($name, $value)
    {
        parent::prepend($name, $value);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function append($name, $value)
    {
        parent::append($name, $value);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function assign($name, $value)
    {
        parent::assign($name, $value);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function reset($name)
    {
        parent::reset($name);
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function end()
    {
        parent::end();
    }

    /**
     * {@inheritDoc}
     * @return void
     */
    public function extend($name)
    {
        parent::extend($name);
    }
```

**Question:** I assume about the same amount of functions that should go inside TwigView would otherwise need to become Twig Tags for TwigView + CakePHP 3.5 to run without changes on Templates?

Then there is also `__set() which I am not sure if TwigView supports it, but it doesnt return $this (why not :P)?

**Comment by markstory** [comment]
Another option I thought of is to implement `__toString()` on View, and return `''`. This would solve the compatibility issue for both this and other plugins.

**Comment by inoas** [comment]
I am going to give this a try before hacking other ways.

**Comment by inoas** [comment]
I gave it a try locally (in my SimpleTwigView ... but it should be the same).
Following **works without being required to change any twig template code**:

### Within your `class TwigView`

```php

    /**
     * {@inheritDoc}
     * @return string
     */
    public function assign($name, $value)
    {
        parent::assign($name, $value);

        return $value;
    }

    /**
     * {@inheritDoc}
     * @return string
     */
    public function __toString()
    {
        return '';
    }
```

### Tested with

```twig
{{ _view.assign('title', __("I'm title"))|none }}

{{ _view.start('header') }}
<p>I'm header</p>
{{ _view.end() }}

{{ _view.start('footer') }}
<p>I'm footer</p>
{{ _view.end() }}
<p>I'm content</p>

{{ _view.fetch('header')|raw }}
{{ _view.fetch('footer')|raw }}
```

@WyriHaximus is this approach good with you?

Would any of you want to have any further setter methods to return their values for BC reasons?

**Comment by WyriHaximus** [comment]
@inoas I'll test it and dive into this issue tomorrow :+1:

**Comment by markstory** [comment]
@inoas I was proposing to implement __toString() on CakePHP's view class.

**Comment by dereuromark** [comment]
@inoas You are dead-wrong. This is not a BC break from the framework perspective.
"Void to sth" is always fully BC.
If the plugin and Twig used the return value of void methods and by accident just worked so far, that is the plugin's problem, not CakePHP core's. Please understand this difference.

That said, the solution now provided seems to fix this in some way. So seems to be all good with the next patch release.

**Comment by robertpustulka** [comment]
Ideally a "native" support for Cake blocks would be great.

Something like:
```twig
{% start 'header' %}
<h1>Title</h1>
{% end %}
```
```twig
{% append 'header' %}
<h2>Subtitle</h2>
{% end %}
```
```twig
{% fetch 'header' %}
```

**Comment by inoas** [comment]
@markstory I am not sure that that is entirely good:

Setter-style-methods (like assign here) that returned strings before would throw notices/warnings as of now. With the `global` change in Cake\View\View itself, these warnings would not longer occur and plugin authors would possibly not know that things broke/changed.

@dereuromark not sure if I am the one who is dead wrong, this time ;-):

1. If the change was from `any-non-void` to `void`; How would that be BC? Say a transformator suddenly storing the transformed value instead of returning it?
2. The change here is from returning `string` to `$this` which is a return type change and that is non-BC, can you confirm this?

@robertpustulka yep, however:

1. do you agree that we should not force people to upgrade their Twig Templates during a minor CakePHP release, let alone they know about the problem. If we find a rather good compromise, It is bad enough that templates will break unless people will update/upgrade to the upcoming 4.x TwigView *as well*. To do that the solution above is fitting, or can you think about anything better?

2. After (1.) we can prep a PR to add Twig-Tags for start, append, prepend, assign, fetch, reset, and end and deprecate the old way to use them?

3. In a future TwigView release we can remove the old way of calling `{{ _view.some_setter() }}`?

**Comment by robertpustulka** [comment]
> The change here is from returning string to $this which is a return type change and that is non-BC, can you confirm this?

The change is from returning `void` to `$this` ([see the code](https://github.com/cakephp/cakephp/blob/3.4.13/src/View/View.php#L774)).

I suspect that you expected that `assign()` would have returned a block content. The behavior has not changed, only the return value has - from nothing to something.

Please, again, get your facts straight before you start telling people that they are wrong.

> do you agree that we should not force people to upgrade their Twig Templates during a minor CakePHP release

Yes. I'm talking about a future plugin release.

**Comment by inoas** [comment]
As `assign()` never returned something despite that the `TwigView` docs made me believe it would, implementing `__toString()` in CakePHP 3.5 like suggested will fix this problem.

I can take care and implement the tags for `start, append, prepend, assign, fetch, reset, end` (tags do not (necessarily) echo) on top of the next major TwigView release.

**Comment by dereuromark** [comment]
@inoas But you complained about 3.5 in particular. But the only change there was https://github.com/cakephp/cakephp/pull/11134 which is BC.
The change regarding assign() seems to be in a very early 3.x version, though. So quite some years ago.

**Comment by inoas** [comment]
@Orken #61 will fix your problem once merged and tagged.

This is the followup issue to track the correct implementation in future https://github.com/WyriHaximus/TwigView/issues/62 for all those interested

**Comment by WyriHaximus** [comment]
4.0.6 has been tagged with a fix for this :+1:

**Comment by inoas** [comment]
Ref: https://github.com/cakephp/cakephp/issues/11276#issue-263070139
