### ISSUE TITLE
Please make a new release for 4.x branch :)

### ISSUE THREAD

**Issue by ADmad** [WyriHaximus/TwigView#72]

**Comment by WyriHaximus** [comment]
yes! Was kinda waiting for your work to be (nearly) done in cake/bake before tagging it. But I'll tag it later today :tada:

**Comment by ADmad** [comment]
I have finished creating all twig templates for bake :). If you have time please take a look and suggest any improvements/fixes as you see fit.

**Comment by WyriHaximus** [comment]
Done, [`4.1.0`](https://github.com/WyriHaximus/TwigView/releases/tag/4.1.0) has been tagged :tada:
