### ISSUE TITLE
Consider removing env() and config() or making them not load by default

### ISSUE THREAD

**Issue by inoas** [WyriHaximus/TwigView#76]
Reason: Use twig to not strictly separate concerns. Like layout authors should not be able to read env or core configuration.

**Comment by WyriHaximus** [comment]
For 4.x they will be loaded by default, with a flag to turn them off. For 5.x that will be reversed. I'll implement this shortly

**Comment by inoas** [comment]
That's great!

**Comment by ADmad** [comment]
@WyriHaximus Sounds good. Though perhaps in 5.x `env` should be changed to a function instead of a filter.
