### ISSUE TITLE
Call to a member function loadTemplate() on null

### ISSUE THREAD

**Issue by vonboth** [WyriHaximus/TwigView#79]
Just upgraded to Cake 3.5.8 and TwigView 4.2.6

My App breaks with 'Call to a member function loadTemplate() on null'

Error in: ROOT/vendor/wyrihaximus/twig-view/src/View/TwigView.php, line 188

For some reason the initialize()-Funktion in TwigView is not called.

Is this a CakePHP issue?

Using versions: 3.5.6 and 4.0.2 works just fine

I will investigate and post a solution if I find one ;-)

**Comment by vonboth** [comment]
My bad ...
Missed parent::initialize() in my AppView class
Sorry!!

**Comment by WyriHaximus** [comment]
No problem, glad to hear you solved your issue :+1:
