### ISSUE TITLE
loadTemplate() on null

### ISSUE THREAD

**Issue by MokniSofien** [WyriHaximus/TwigView#82]
return $this->render('/Sofien/sofien', array('name' => $sof));

i get this error : Call to a member function loadTemplate() on null

how to fix ?

**Comment by WyriHaximus** [comment]
Hey @MokniSofien have you tried updating to the latest version? A recent change in CakePHP can cause that error but a fix has been released for that.

**Comment by Labelsuisse** [comment]
Hey,
I have a same problem.
Cakephp v3.5.1 
Twig-view v4.3

Thank's for your support

**Comment by Labelsuisse** [comment]
Hey @WyriHaximus,

I solved my problem. I had elect to call the parent in the initialization of the AppView.

Sorry for the inconvenience and thank you

**Comment by WyriHaximus** [comment]
:+1:
