### ISSUE TITLE
Name conflict with Twig default filter

### ISSUE THREAD

**Issue by nojimage** [WyriHaximus/TwigView#87]
TwigView 4.3.4

I want to use Twig's [format](https://twig.symfony.com/doc/1.x/filters/format.html) filter.

```
{{ '#%07d' | format(order.id) }}
```

But, using this plugin will cause `Cake\I18n\Number::format()` to be called.

Is there a good way to call Twig's `format`?

**Comment by nojimage** [comment]
In TwigView 4.1, I was able to call Twig's `format`.

**Comment by nojimage** [comment]
hmm, I found this commit. https://github.com/WyriHaximus/TwigView/commit/f9be3b19c63ad1cf8bbf43ce39278e2d81ab4ba3
Before this commit, the Number extension was not enabled, Twig's `format` filter could be called.

**Comment by WyriHaximus** [comment]
Good catch, feel like up to creating a PR to change `format` to `number_format` at https://github.com/WyriHaximus/TwigView/blob/4.x/src/Lib/Twig/Extension/Number.php#L31 ?

**Comment by WyriHaximus** [comment]
A new version has been tagged: https://github.com/WyriHaximus/TwigView/releases/tag/4.3.5
