### ISSUE TITLE
mb_convert_encoding(): Illegal character encoding specified

### ISSUE THREAD

**Issue by dereuromark** [WyriHaximus/TwigView#94]
When trying to use TwigView rendering, I got

> mb_convert_encoding(): Illegal character encoding specified

in vendor/twig/twig/lib/Twig/Extension/Core.php:1137

Any idea what this is? It is a basic ascii template with simple variables.
```php
	$data = [
		'name' => 'Foo',
		'namespace' => 'foo',
		'plugin' => 'cakephp-foo',
	];

	$this->renderer->set($data);

	$content = $this->renderer->generate('foo');
```

**Comment by WyriHaximus** [comment]
Sorry for the late response my github box got swamped due to automated dependency bumping. So are you using this for CakePHP 3 or the upcoming for 4? (Should fix it in both tbh.)

**Comment by dereuromark** [comment]
cake3

**Comment by WyriHaximus** [comment]
Cheers, looking into it tonight

**Comment by dereuromark** [comment]
You can easily reproduce it by commenting out `'encoding' => 'utf-8',`
https://github.com/dereuromark/cakephp-dto/blob/master/tests/bootstrap.php#L32
and running the tests on that plugin.

**Comment by WyriHaximus** [comment]
@dereuromark sorry for the delay #101 is up to fix this

**Comment by WyriHaximus** [comment]
Tagged `4.3.8` with #101
